<h5>Encrypt a folder</h5>
<p>Secure your files with a self chosen password. Alternatively you can get one generated by the application.</p>
<br>
<br>
<div class="table">
    <div class="thead">
        <div class="tr">
            <div class="th c1">Status</div>
            <div class="th c2">Folder</div>
            <div class="th c3">Options</div>
        </div>
    </div>
    <div class="tbody">
        <div class="tr">
            <div class="td c1">
                <img src="images/encrypt.png">
            </div>
            <div class="td c2">
                file://test/abc2/abe/test
            </div>
            <div class="td c3">
                <a class="button">Decrypt</a>
                <a class="button">Remove</a>
            </div>
        </div>
        <div class="tr">
            <div class="td c1">

            </div>
            <div class="td c2">
                file://test/abc/test
            </div>
            <div class="td c3">
                <a class="button">Encrypt</a>
                <a class="button">Remove</a>
            </div>
        </div>
    </div>
</div>
<br><br>
<div class="center-button">
    <a href="#" class="button saveSettings">Add folder</a>
</div>